### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/article-w3cdataws2019-graphql#1]
First version of my position statement for the [W3C Workshop on Web Standardization for Graph Data](https://www.w3.org/Data/events/data-ws-2019/cfp.html) is done, could you have a look at it @RubenVerborgh and @mielvds?

Side-question; do I include you as co-authors here?

**Comment by RubenVerborgh** [comment]
Reviewed, can I have push permissions?

**Comment by RubenVerborgh** [comment]
Regarding authorship, I don't mind, but it might help people connect things to the broader context. A vision statement endorsed by all of thus might be stronger.

**Comment by RubenVerborgh** [comment]
Reviewed in 4399f6484b811676f68e94f74c73295114a627f0.

**Comment by mielvds** [comment]
Reviewed in https://github.com/rubensworks/article-w3cdataws2019-graphql/commit/8a66bb22082a6643f9decfa40cefb585aa0dad9c.

**Comment by rubensworks** [comment]
Thanks all!
